### ISSUE TITLE
Minor Issue regarding instructions

### ISSUE THREAD

**Issue by MaxwellDiffusion** [ypaul21/Clapeyron.jl#21]
I had issues regarding the installation instructions.

Using:
Pkg> add git@github.com:ypaul21/OpenSAFT.jl.git
Lead to a repeated asking of a private/public ssh-key. Seems to be an open issue wen downloading private repos in julia (see e.g. https://discourse.julialang.org/t/pkg-clone-keeps-asking-for-my-ssh-key/15155)

A trivial but yet effective solution was to use instead:
Pkg> add https://github.com/ypaul21/Clapeyron.jl.git

**Comment by ypaul21** [comment]
Hi! Thanks for bringing this up! We actually have amended instructions on our development branch:

https://github.com/ypaul21/Clapeyron.jl/tree/development

We have definitely left our master branch for a bit too long, and we have made a lot of significant changes to our package in our development branch since then. We are just going to tidy it up a bit, and we will very soon be merging all changes to master (and hopefully make much more frequent updates to it directly after that).

**Comment by MaxwellDiffusion** [comment]
Ahh true! Thanks for the fast reply.
