### ISSUE TITLE
The log in ahc

### ISSUE THREAD

**Issue by Borrdom** [ypaul21/Clapeyron.jl#24]
Apart from the old function names due to the differences of the master/development branches in all notebook examples.

I found that in Gross2001.ipynb for all components, the "sat_pure" functions throws a log error when fed temperatures near the critical temperature (starting at around 20 Kelvin below it).

I found that the issue is caused by negative numbers in the expression "log(\zeta3-1)" part of the hard-sphere contribution a_hs. I think the solver moves outside the feasible region when trying to find saturation. 
Maybe bounding the input domain with log(max(\zeta3-1,1E-330)) will do the trick.

**Comment by pw0908** [comment]
Hi MaxwellDiffusion, 

Thanks a lot for pointing this out; this is an issue we've been wrestling with for a while. I've taken a look at the specific case you pointed out and, weirdly enough, it originates from our initial guess calculator. We've tried to use a method which obtains the initial guess from the second virial approximation where we find the root in the vapour region and determine the liquid phase corresponding to the same pressure. The issue is, as you approach the critical point, the liquid root disappears and our volume solver throws an error. I've dealt with this by catching the error in those cases and simply using the volume corresponding to a packing fraction of 0.25 as an initial guess instead. This has greatly improved our sat_pure function near the critical point so thank you very much for pointing it out!

We still encounter issues when the solver moves out of the feasible region (although this is more equation and system-specific); I will try out your suggestion since that seems to do the trick!

If you encounter any other specific issues with any of our solvers, please let us know and feel free to contribute as well!
