### ISSUE TITLE
Wrong functions in example notebooks

### ISSUE THREAD

**Issue by FranciscoASanchez** [ypaul21/Clapeyron.jl#43]
Dear all,
I'm new in Julia, and quite exited with this project. I'm a researcher and I've been developing yet another GC EOS since 2008, and I'd like to make it available. 
So, I've been trying to follow some of the pynb examples, but it seems that the function names have been redefined or something.
For example, in the _Gross2002.ipynb_, the package is still called _OpenSAFT_.
Also, it seems that some function definitions have changed, as for example `system`. When I execute it I get
`UndefVarError: system not defined`

`Stacktrace:`
` [1] top-level scope`
`   @ In[3]:2`
` [2] eval`
`   @ ./boot.jl:360 [inlined]`
` [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)`
`   @ Base ./loading.jl:1094`
And it seems to work now with a function directly called `PCSAFT` instead. The same goes for `get_crit_pure` which seems to be now just `crit_pure`.

The example notebooks are great, but they seems needing an update.  Since I'm starting, and they serve as exercises, I can do it; but I need kind of manual that I'm not sure how to get all the correct function names. Is there a manual which I can access?
Regards

**Comment by ypaul21** [comment]
Hi! Thanks for checking out this project! Coming from other languages, I think you’ll find Julia to be a really fun and powerful tool. :)

We have indeed made major changes to our API. It looks like we somehow missed a few blocks in some of the notebooks. We’ll try to get it fixed very soon!

In the meantime, do check out our documentation for some of the stuff that we can do. 

https://ypaul21.github.io/Clapeyron.jl/dev/user_guide/basic_usage/

I actually just realised that our documentation is now also slightly ahead of the latest Clapeyron release (0.2.1). We have added a number of new features like activity models since then. We’ll try to get a new update pushed to the JuliaHub too. 

For the time being, if you’d like to try out the latest version that we have on our GitHub, you may do so by entering Pkg mode by typing `]` in the Julia REPL, and then typing

```
Pkg> add https://github.com/ypaul21/Clapeyron.jl
```

Do let us know if you run into any issues!

**Comment by FranciscoASanchez** [comment]
So, there *was already* a man page, but I missed it. Thanks a lot, Paul.
